USE QLDETAI
GO

-- 1
SELECT BM.MABM, BM.TENBM
FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
			  JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
			  JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
WHERE CV.TENCV LIKE N'%PHÂN TÍCH%' 
GROUP BY BM.TENBM, BM.MABM
HAVING COUNT(DISTINCT GV.MAGV) >= ALL(SELECT COUNT(DISTINCT GV.MAGV)
									  FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
													   JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
									  WHERE CV.TENCV LIKE N'%PHÂN TÍCH%' 
									  GROUP BY GV.MABM)

-- 2
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN KHOA K ON K.TRUONGKHOA = GV.MAGV
				 JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
GROUP BY K.MAKHOA, GV.MAGV, GV.HOTEN
HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(BM.MABM)
									  FROM GIAOVIEN GV JOIN KHOA K ON K.TRUONGKHOA = GV.MAGV
													   JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
									  GROUP BY K.MAKHOA, GV.MAGV, GV.HOTEN)
UNION 
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV LEFT JOIN KHOA K ON K.TRUONGKHOA = GV.MAGV
				 JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
				 JOIN GIAOVIEN GV2 ON GV2.MABM = BM.MABM
				 LEFT JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
GROUP BY K.MAKHOA, GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.GVCNDT) >= ALL(SELECT COUNT(DISTINCT DT.GVCNDT)
										FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
													  JOIN BOMON BM ON GV.MABM = BM.MABM
													  JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
										GROUP BY K.MAKHOA, K.TRUONGKHOA)

-- 3
SELECT DT.MADT, DT.TENDT, DT.CAPQL, DT.KINHPHI, COUNT(CV.MADT) AS SLCV
FROM DETAI DT LEFT JOIN CONGVIEC CV ON DT.MADT = CV.MADT
GROUP BY DT.MADT, DT.TENDT, DT.CAPQL, DT.KINHPHI
HAVING DT.KINHPHI >= ALL(SELECT DT2.KINHPHI
							  FROM DETAI DT2 
							  WHERE DT2.CAPQL = DT.CAPQL)

-- 4
-- BI CHIA: GV KHOA HOA
-- CHIA: TAT CA CAC DT CAP TRUONG DO GV KHOA HOA CN
SELECT GV.MAGV, GV.HOTEN, TG.MADT
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
				 JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE K.TENKHOA = N'HÓA HỌC' AND NOT EXISTS((SELECT DT.MADT
											 FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
														   JOIN BOMON BM ON GV.MABM = BM.MABM
														   JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
											 WHERE K.TENKHOA = N'HÓA HỌC')
											 EXCEPT
											(SELECT DT.MADT
											 FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
															  JOIN KHOA K1 ON BM1.MAKHOA = K1.MAKHOA
															  JOIN THAMGIADT TG1 ON GV1.MAGV = TG1.MAGV
															  JOIN DETAI DT1 ON TG1.MADT = DT1.MADT
											 WHERE K.TENKHOA = N'HÓA HỌC' AND GV.HOTEN = GV1.HOTEN AND GV.MAGV = GV1.MAGV))

-- 5
CREATE PROC SP_XOATGDT @MAGV CHAR(5), @MADT CHAR(3), @STT INT
AS
BEGIN
	IF (NOT EXISTS(SELECT* 
				   FROM THAMGIADT 
				   WHERE MAGV = @MAGV AND MADT = @MADT AND STT = @STT))
		RETURN 0

	IF (EXISTS(SELECT*
			   FROM THAMGIADT
			   WHERE KETQUA IS NULL AND MAGV = @MAGV AND MADT = @MADT AND STT = @STT))
		RETURN 0

	DECLARE @SLGV INT, @SLDT INT

	SELECT @SLGV = COUNT(DISTINCT MAGV) 
    FROM THAMGIADT 
    WHERE MADT = @MADT 

    IF (@SLGV = 1)
        RETURN 0

    SELECT @SLDT = COUNT(DISTINCT MADT) 
    FROM THAMGIADT 
    WHERE MAGV = @MAGV 

    IF (@SLDT = 1)
        RETURN 0

	DELETE FROM THAMGIADT WHERE MAGV = @MAGV AND MADT = @MADT AND STT = @STT 
	RETURN 1
END

DECLARE @KQ INT
EXEC @KQ = SP_XOATGDT '003', '001', 2
IF (@KQ = 1)
	PRINT 'XOA THANH CONG'
ELSE PRINT 'XOA KHONG THANH CONG'