USE QLDETAI
GO

--Q35
SELECT DISTINCT LUONG
FROM GIAOVIEN 
WHERE LUONG >= ALL(SELECT LUONG FROM GIAOVIEN)

--Q36
SELECT*
FROM GIAOVIEN 
WHERE LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN)

--Q37
SELECT LUONG
FROM GIAOVIEN 
WHERE MABM = 'HTTT' AND LUONG = (SELECT MAX(LUONG) 
								FROM GIAOVIEN 
								GROUP BY MABM
								HAVING MABM = 'HTTT')

--Q38
SELECT HOTEN
FROM GIAOVIEN
WHERE MABM = 'HTTT' AND YEAR(NGSINH) = (SELECT MIN(YEAR(NGSINH)) 
										FROM GIAOVIEN
										GROUP BY MABM
										HAVING MABM = 'HTTT')

--Q39
SELECT HOTEN
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.MAKHOA = 'CNTT' AND NGSINH = (SELECT MAX(NGSINH) 
										FROM GIAOVIEN GV
										JOIN BOMON BM ON GV.MABM = BM.MABM
										JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
										GROUP BY K.MAKHOA
										HAVING K.MAKHOA = 'CNTT')

--Q40
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE LUONG >= ALL(SELECT LUONG FROM GIAOVIEN)
				
--Q41
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE LUONG = ANY(SELECT MAX(LUONG) 
				FROM GIAOVIEN
				GROUP BY MABM)

--Q42
SELECT TENDT
FROM DETAI 
EXCEPT
SELECT TENDT
FROM GIAOVIEN GV 
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE GV.HOTEN = N'NGUYỄN HOÀI AN'

--Q43
SELECT DT.TENDT, GV.HOTEN
FROM GIAOVIEN GV 
JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
WHERE DT.MADT NOT IN(SELECT MADT 
					FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
					WHERE HOTEN = N'NGUYỄN HOÀI AN')

--Q44
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE MAKHOA = 'CNTT' AND NOT EXISTS(SELECT* 
									FROM THAMGIADT TG
									WHERE TG.MAGV = GV.MAGV)

--Q45
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS(SELECT*
				FROM THAMGIADT TG
				WHERE TG.MAGV = GV.MAGV)

--Q46
SELECT HOTEN
FROM GIAOVIEN GV
WHERE LUONG > (SELECT LUONG
				FROM GIAOVIEN
				WHERE HOTEN = N'NGUYỄN HOÀI AN')

--Q47
SELECT GV.HOTEN
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
WHERE MAGV = ANY(SELECT MAGV FROM THAMGIADT)

--Q48
SELECT GV1.HOTEN
FROM GIAOVIEN GV1 JOIN GIAOVIEN GV2 ON GV1.MABM = GV2.MABM AND GV1.MAGV != GV2.MAGV
WHERE GV1.HOTEN = GV2.HOTEN AND GV1.PHAI = GV2.PHAI

--Q49
SELECT HOTEN
FROM GIAOVIEN
WHERE LUONG > ANY(SELECT LUONG 
				FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				WHERE BM.TENBM = N'CÔNG NGHỆ PHẦN MỀM')

--Q50
SELECT HOTEN
FROM GIAOVIEN
WHERE LUONG > ALL(SELECT MAX(LUONG)
				FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN')

--Q51
SELECT TENKHOA
FROM KHOA K, BOMON BM, GIAOVIEN GV
WHERE K.MAKHOA = BM.MAKHOA AND BM.MABM = GV.MABM
GROUP BY K.TENKHOA, K.MAKHOA
HAVING COUNT(MAGV) >= ALL(SELECT COUNT(MAGV)
						FROM GIAOVIEN GV, KHOA K , BOMON BM
						WHERE K.MAKHOA = BM.MAKHOA AND BM.MABM = GV.MABM
						GROUP BY K.TENKHOA, K.MAKHOA)

--Q52
SELECT HOTEN
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(MADT) >= ALL(SELECT COUNT(MADT)
						FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
						GROUP BY MAGV)

--Q53
SELECT MABM
FROM GIAOVIEN 
GROUP BY MABM
HAVING COUNT(MAGV) >= ALL(SELECT COUNT(MAGV)
							FROM GIAOVIEN
							GROUP BY MABM)

--Q54
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.HOTEN, BM.TENBM, TG.MADT
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
							FROM GIAOVIEN GV 
							JOIN BOMON BM ON GV.MABM = BM.MABM
							JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
							GROUP BY GV.HOTEN, BM.TENBM, TG.MADT)

--Q55
SELECT GV.HOTEN
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE BM.MABM = 'HTTT'
GROUP BY GV.HOTEN, BM.TENBM, TG.MADT
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
							FROM GIAOVIEN GV 
							JOIN BOMON BM ON GV.MABM = BM.MABM
							JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
							WHERE BM.MABM = 'HTTT'
							GROUP BY GV.HOTEN, BM.TENBM, TG.MADT)
						
--Q56
SELECT HOTEN, TENBM
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
GROUP BY HOTEN, TENBM, GV.MAGV
HAVING COUNT(GV.MAGV) >= ALL(SELECT COUNT(GV.MAGV)
							FROM GIAOVIEN GV JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
							GROUP BY GV.MAGV)

--Q57
SELECT HOTEN
FROM GIAOVIEN GV 
JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY HOTEN, MAGV
HAVING COUNT(MADT) >= ALL(SELECT COUNT(MADT)
						FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
						GROUP BY MAGV)